version: '3'

services:
  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile
    ports:
      - 443:443
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception-net
    depends_on:
      - wordpress

  mariadb:
    build:
      context: mariadb
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "3306"
    networks:
      - inception-net
    volumes:
      - mariadb:/var/lib/mysql
  
  wordpress:
    env_file: .env
    build:
      context: wordpress
      dockerfile: Dockerfile
    ports:
      - 9000
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception-net
    depends_on:
      - mariadb

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/aelidrys/data/wordpress'
  mariadb:
    driver: local
    driver_opts:
      type: 'none' 
      o: 'bind'
      device: '/home/aelidrys/data/mariadb'
networks:
  inception-net: