version: '3'

services:
  nginx:
    container_name: static_web
    build: static_web
    ports:
      - 8082:8500
    volumes:
      - tools:/var/www/html

volumes:
  tools:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/aelidrys/Desktop/inception/srcs/requirements/bonus/static_web/tools' 